import { Star } from "lucide-react";

export default function Hero() {
  return (
    <section className="mt-40 md:mt-28 text-center flex flex-col gap-4">
      <div className="relative mx-auto w-70 h-70 md:w-72 md:h-72">
        <div className="absolute top-4 right-4 bg-white px-3 py-1 font-semibold rounded-full flex items-center gap-2 shadow">
          <Star size={18} fill="#FE7F9C" stroke="none" />
          <span>5.0</span>
        </div>

        <div className="absolute bottom-4 -left-4 bg-[#FE7F9C] px-4 py-1 font-semibold rounded-full text-white shadow">
          From $20
        </div>
        <img
          src="./images/classic1.webp"
          alt="Classic New York Cheesecake, image generated by ChatGPT, created by Davonne Vigil."
          loading="lazy"
          className="w-full h-full rounded-full border-4 border-white object-cover"
        />
      </div>
      <p className="text-gray-500 mx-auto tracking-widest max-w-xs">
        STATE OF THE ART CHEESECAKE SINCE 1993
      </p>
      <h2 className="text-7xl font-nic">Velvet Goodness</h2>
      <p className="italic text-gray-500 text-center text-2xl">
        where every bite hits
      </p>
      <p className="max-w-sm text-gray-500 mx-auto mt-2">
        Family owned business making cheesecake. Made fresh daily, all natural
        ingredients, and recipes perfected over 30 years.
      </p>
      <div className="flex flex-col md:flex-row gap-8 mx-auto my-4">
        <button className="bg-[#FE7F9C] p-3 rounded-full text-white">
          Order for Delivery →
        </button>
        <button className="bg-white text-pink-300 p-3 rounded-full">
          View Full Menu
        </button>
      </div>
      <div className="flex justify-center my-8">
        <div className="h-0.5 w-60 md:w-90  bg-[#FE7F9C]/20"></div>
      </div>
    </section>
  );
}
