import { CakeSlice } from "lucide-react";
import { useState } from "react";
import { motion } from "motion/react";

export default function Newsletter() {
  const [email, setEmail] = useState("");
  const [isSubmitted, setIsSubmitted] = useState(false);

  const handleSubmit = (e: { preventDefault: () => void }) => {
    e.preventDefault();

    if (!email) return;

    setIsSubmitted(true);
    setEmail("");
  };

  return (
    <section className="bg-[#FE7F9C] text-white">
      <div className="max-w-3xl mx-auto p-20">
        <div className="flex flex-col gap-8 justify-center items-center">
          <CakeSlice className="w-10 h-10" />

          <h2 className="text-5xl font-dm text-center">Slice of the cake</h2>

          <p className="max-w-md text-center text-lg">
            Subscribe to our newsletter for new flavors, specials, and of course
            a special treat for your birthday! Bonus for signing up, 20% off
            your first order.
          </p>

          {!isSubmitted ? (
            <form
              onSubmit={handleSubmit}
              className="flex flex-col md:flex-row gap-4"
            >
              <input
                type="email"
                value={email}
                placeholder="Enter Your Email"
                className="p-2 bg-white/20 w-60 md:w-80 focus:outline-none"
                onChange={(e) => setEmail(e.target.value)}
                required
              />

              <button
                type="submit"
                className="bg-white/60 cursor-pointer hover:scale-105 w-60 md:w-40 rounded-lg tracking-widest text-black p-2"
              >
                Subscribe
              </button>
            </form>
          ) : (
            <>
              <motion.div
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                whileInView={{ opacity: 1 }}
                viewport={{ once: true }}
                transition={{ duration: 1 }}
                className="text-center max-w-md text-md p-8 md:text-lg font-semibold bg-white/20 rounded-sm cursor-pointer shadow-md"
                onClick={() => setIsSubmitted(false)}
              >
                Thank you for subscribing! Check your inbox for your discount
                code!
                <img
                  src="./images/cheesecake.webp"
                  alt="Strawberry CheeseCake Design, image Generated by ChatGPT, created by Davonne Vigil"
                  loading="lazy"
                  className=" rounded-sm  max-w-xs md:max-w-sm mx-auto p-2"
                />
              </motion.div>
            </>
          )}

          <p className="text-center max-w-md text-xs md:text-sm mb-2">
            Unsubscribe at anytime. We love our customers and your privacy.
          </p>
        </div>
      </div>
    </section>
  );
}
