import { CakeSlice } from "lucide-react";
import { useState } from "react";
import { ToastContainer, toast, Slide } from "react-toastify";

type FormData = {
  fullName: string;
  address: string;
  email: string;
  cardNumber: string;
  expiry: string;
  cvv: string;
  promo: string;
};

export default function CheckoutForm() {
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [formData, setFormData] = useState<FormData>({
    fullName: "",
    address: "",
    email: "",
    cardNumber: "",
    expiry: "",
    cvv: "",
    promo: "",
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const cheesecakeOrderSent = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsSubmitted(true);
    toast("Order is confirmed! Ready in 15 minutes at pick up location!", {
      className: "font-bold",
      ariaLabel: "Success alert",
      role: "success",
      progressClassName: "bg-red-400",
    });
  };
  return (
    <section>
      <form
        onSubmit={cheesecakeOrderSent}
        className="mt-12 bg-black/70 p-8 max-w-7xl  h-full mx-auto px-8"
      >
        <h1
          className="font-nic text-5xl text-white 
         flex gap-4 items-center justify-center mt-2"
        >
          <CakeSlice width={30} height={30} />
          Checkout
          <CakeSlice width={30} height={30} />
        </h1>
        <p className="text-white max-w-sm text-center mx-auto mt-2 text-lg">
          {" "}
          And every order comes with a side of apple pie and ice cream on us.
        </p>

        <div className="mt-8 font-serif">
          <div className="flex flex-col md:flex-row gap-8">
            <div className="flex flex-col mx-auto gap-4 w-60 md:w-sm">
              <input
                type="text"
                required
                onChange={handleChange}
                placeholder="Full Name"
                className="p-2 bg-white outline-none"
              />
              <input
                required
                onChange={handleChange}
                type="address"
                placeholder="Address"
                className="p-2 bg-white outline-none"
              />

              <input
                type="email"
                required
                onChange={handleChange}
                placeholder="E-mail Address"
                className="p-2 bg-white outline-none"
              />

              <input
                required
                onChange={handleChange}
                type="text"
                placeholder="Credit Card Number"
                className="p-2 bg-white outline-none"
              />
              <div className="flex flex-col md:flex-row gap-4">
                <div className="flex gap-2">
                  <input
                    required
                    onChange={handleChange}
                    type="text"
                    placeholder="expir"
                    className="p-2 bg-white outline-none w-20"
                  />

                  <input
                    required
                    onChange={handleChange}
                    type="text"
                    placeholder="cvv"
                    className="p-2 bg-white outline-none w-20"
                  />
                </div>

                <input
                  onChange={handleChange}
                  type="text"
                  placeholder="PROMO CODE"
                  className="p-2 bg-white outline-none w-40"
                />
              </div>

              <button className="p-2 outline-none rounded-md bg-[#FE7F9C] font-nic text-2xl cursor-pointer mt-4 transition duration-300 hover:scale-105">
                Submit
              </button>
            </div>
            <img
              src="./images/applePie.webp"
              className="w-60 md:w-2xl object-cover h-80 mt-2"
              alt="Apple Pie, imaged generated by ChatGPT, created by Davonne Vigil"
            />
          </div>
          {isSubmitted && (
            <section className="flex flex-col justify-center items-center mt-8 gap-2 text-white">
              <h2 className="font-serif text-2xl">Order has been received!</h2>
              <p className="font-serif text-xl max-w-lg text-center">
                Pick up location: 2318 Sully Lane, Forks, WA 90210
              </p>
            </section>
          )}
        </div>
      </form>
      <ToastContainer
        position="top-center"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick={true}
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        transition={Slide}
        progressClassName="bg-red-500"
      />
    </section>
  );
}
