export default function PickUpLocation() {
  const scrollToSection = (sectionId: string) => {
    const element = document.getElementById(sectionId);
    if (element) {
      element.scrollIntoView({ behavior: "smooth" });
    } else {
      // If element doesn't exist on current page, navigate to home and scroll
      window.location.href = `/#${sectionId}`;
    }
  };

  return (
    <section className="flex flex-col justify-center items-center gap-4 my-10 text-center">
      <div className="relative mx-auto">
        <div className="absolute inset-0 flex  items-center justify-center z-0 mt-20 ">
          <div className="absolute text-[26vw] md:text-[18vw] font-bold font-dm tracking-wide text-gray-400/20">
            Mmmm
          </div>
        </div>

        <h2 className="font-nic text-4xl md:text-5xl ">Order Confirmed! </h2>
        <p className="text-lg md:text-xl text-center max-w-xs md:max-w-2xl mt-4">
          <span className="font-bold"> Pick up location:</span> 2319 Sully Lane,
          Forks, WA 90210 in 15 minutes!
        </p>
        <p className="text-lg md:text-xl text-center max-w-xs md:max-w-2xl mt-2">
          {" "}
          Comes with a free slice of apple pie and ice cream!
        </p>

        <img
          src="./images/applePie.webp"
          alt="Apple Pie and Ice Cream, image generated by AI"
          className="w-60 h-60 md:w-90 md:h-90 object-cover rounded-3xl shadow-xs shadow-white shake mt-12"
        />
      </div>
      <button
        onClick={() => scrollToSection("home")}
        className="p-2 mt-10 outline-none rounded-md text-white bg-[#FE7F9C] font-dm text-lg cursor-pointer transition duration-300 hover:scale-105"
      >
        Continue to Site
      </button>
    </section>
  );
}
